name: Update Dashboard Version

on:
  push:
    branches: [main]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get date-based version
        run: echo "VERSION=$(date +'%Y.%m.%d')_build$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Replace version string in dashboard.sh
        run: |
          sed -i -E "s/CURRENT_VERSION=\"[^\"]+\"/CURRENT_VERSION=\"$VERSION\"/" server/dashboard.sh

      - name: Check if dashboard.sh changed
        id: check_changes
        run: |
          if git diff --quiet server/dashboard.sh; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push updated version
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Bot"
          git commit -am "🚀 Auto bump version to $VERSION"
          git push
